FROM golang:1.21-alpine
  
  # Install git
RUN set -ex; \
apk update; \
apk add --no-cache git
  
  # Set working directory 
WORKDIR /go/src/github.com/pennsieve/pennsieve-go-core
  
  # Run tests
CMD CGO_ENABLED=0 go test -p 1 -v ./...