version: '3'

networks:
  core-tests:
    driver: bridge

services:
  # Test Container for running tests locally
  local_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - dynamodb
      - pennsievedb
    env_file:
      - dockertest.env
    environment:
      - DYNAMODB_URL=http://dynamodb:8000
      - POSTGRES_HOST=pennsievedb
    volumes:
      - $PWD:/go/src/github.com/pennsieve/pennsieve-go-core
    networks:
      - core-tests

  # CI Container for running tests on Jenkins
  ci_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - dynamodb-ci
      - pennsievedb-ci
    env_file:
      - dockertest.env
    environment:
      - DYNAMODB_URL=http://dynamodb-ci:8000
      - POSTGRES_HOST=pennsievedb-ci
    volumes:
      - $PWD:/go/src/github.com/pennsieve/pennsieve-go-core
    networks:
      - core-tests

  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./test-dynamodb-data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - core-tests

  dynamodb-ci:
    image: amazon/dynamodb-local
    restart: always
    volumes:
      - ./test-dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    networks:
      - core-tests

  pennsievedb:
    image: pennsieve/pennsievedb:V20221102133799-seed
    restart: always
    ports:
      - "5432:5432"
    networks:
      - core-tests

  pennsievedb-ci:
    image: pennsieve/pennsievedb:V20221102133799-seed
    restart: always
    networks:
      - core-tests



