# This is a basic workflow to help you get started with Actions

name: Publish-Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*.*.*'  # Match anything resembling semver

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  read-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.read-tag.outputs.tag }}
    steps:
      - name: Read tag
        id: read-tag
        shell: bash  # Needed so that variable expansion operators work properly:
        run: |
          echo "::set-output name=tag::${GITHUB_REF:10}"  # Export just the tag name, e.g. "0.0.1" instead of "refs/tags/0.0.1" as a step output

  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload-url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

